Entity/Consultation.php
<?php

namespace Chill\HealthBundle\Entity;

use Chill\MainBundle\Entity\HasScopeInterface;
use Chill\MainBundle\Entity\HasCenterInterface;

/**
 * Consultation
 * 
 * The state of the consultation can be :
 * 
 * - draft (the consultation may be updated) ;
 * - closed (the consultation cannot be update);
 * 
 * The fact that the consultation can be updated or not, depending on his state,
 * is handled by ConsultationVoter
 */
class Consultation implements HasScopeInterface, HasCenterInterface
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $date;

    /**
     * @var \Chill\PersonBundle\Entity\Person
     */
    private $patient;

    /**
     * @var \Chill\MainBundle\Entity\User
     */
    private $author;

    /**
     * @var \Chill\MainBundle\Entity\Scope
     */
    private $circle;
    
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $medications;
    
    /**
     * The state of the consultation. 
     * 
     * May be "draft" or "closed"
     *
     * @var string
     */
    private $state = self::STATE_DRAFT;
    
    /**
     * The consultation is draft an can be updated
     */
    const STATE_DRAFT = 'draft';
    
    /**
     * The consultation is closed and cannot be update
     */
    const STATE_CLOSED = 'closed';
    
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->medications = new \Doctrine\Common\Collections\ArrayCollection();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Consultation
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set patient
     *
     * @param \Chill\PersonBundle\Entity\Person $patient
     *
     * @return Consultation
     */
    public function setPatient(\Chill\PersonBundle\Entity\Person $patient = null)
    {
        $this->patient = $patient;

        return $this;
    }

    /**
     * Get patient
     *
     * @return \Chill\PersonBundle\Entity\Person
     */
    public function getPatient()
    {
        return $this->patient;
    }

    /**
     * Set author
     *
     * @param \Chill\MainBundle\Entity\User $author
     *
     * @return Consultation
     */
    public function setAuthor(\Chill\MainBundle\Entity\User $author = null)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return \Chill\MainBundle\Entity\User
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set circle
     *
     * @param \Chill\MainBundle\Entity\Scope $circle
     *
     * @return Consultation
     */
    public function setCircle(\Chill\MainBundle\Entity\Scope $circle = null)
    {
        $this->circle = $circle;

        return $this;
    }

    /**
     * Get circle
     *
     * @return \Chill\MainBundle\Entity\Scope
     */
    public function getCircle()
    {
        return $this->circle;
    }
    
    /**
     * alias for self::getCircle()
     * 
     * @return \Chill\MainBundle\Entity\Scope
     */
    public function getScope()
    {
        return $this->getCircle();
    }

        /**
     * Add medication
     *
     * @param \Chill\HealthBundle\Entity\Medication $medication
     *
     * @return Consultation
     */
    public function addMedication(\Chill\HealthBundle\Entity\Medication $medication)
    {
        $this->medications[] = $medication;

        return $this;
    }

    /**
     * Remove medication
     *
     * @param \Chill\HealthBundle\Entity\Medication $medication
     */
    public function removeMedication(\Chill\HealthBundle\Entity\Medication $medication)
    {
        $this->medications->removeElement($medication);
    }

    /**
     * Get medications
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMedications()
    {
        return $this->medications;
    }
    
    public function getCenter()
    {
        return $this->getPatient()->getCenter();
    }
    
    public function getState()
    {
        return $this->state;
    }

    public function setState($state)
    {
        $this->state = $state;
        
        return $this;
    }



}

Form/MedicationType.php
<?php

namespace Chill\HealthBundle\Form;

use Symfony\Component\Form\AbstractType;
use Chill\HealthBundle\Form\Type\AdministrationFrequencyType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Chill\HealthBundle\Form\Type\CodeType;
use Chill\HealthBundle\Form\DataTransformer\ConsultationTransformer;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Chill\HealthBundle\Form\Type\UcumType;


/**
 * Form to add / remove medication
 */
class MedicationType extends AbstractType
{
    
    /**
     *
     * @var ConsultationTransformer
     */
    private $consultationTransformer;
    
    public function __construct(ConsultationTransformer $consultationTransformer)
    {
        $this->consultationTransformer = $consultationTransformer;
    }

        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateFrom')
            ->add('substance', CodeType::class, 
                [
                    'type' => 'substance',
                    'placeholder' => 'Choose a substance',
                    'required' => false
                ])
            ->add('substance_string', TextType::class, array(
                'required' => false
            ))
            ->add('doseQuantityValue')
            ->add('doseQuantityUnit', UcumType::class)
            ->add('routeOfAdministration', CodeType::class,
                [
                    'type' => 'route_of_administration',
                    'placeholder' => 'Choose a route of administration'
                ])
            //->add('administrationUnitCode')
            ->add('administrationFrequency', AdministrationFrequencyType::class)
            ->add('dateTo')
            ->add('modeDelivrance', TextareaType::class, array(
                'required' => false
            ))
            ->add('neverPublish', ChoiceType::class, [
                'choices' => [
                    'never publish' => true,
                    'allow publication' => false
                ],
                'choices_as_values' => true,
                'empty_data' => false
            ])
            ->add('consultation', HiddenType::class)
        ;
        
        $builder->get('consultation')
            ->addModelTransformer($this->consultationTransformer)
            ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Chill\HealthBundle\Entity\Medication'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'chill_healthbundle_medication';
    }
}

Controller/ConsultationController.php
<?php

namespace Chill\HealthBundle\Controller;

use Chill\HealthBundle\Form\CloseConsultationType;
use Chill\HealthBundle\Entity\Consultation;
use Chill\HealthBundle\Security\Authorization\ConsultationVoter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Chill\HealthBundle\Entity\Medication;
use Chill\HealthBundle\Form\MedicationType;
use Chill\PersonBundle\Security\Authorization\PersonVoter;
use Symfony\Component\Security\Core\Role\Role;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ConsultationController extends Controller
{
    /**
     * 
     * @param int $id personId
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws type
     */
    public function listAction($person_id)
    {
        /* @var $person \Chill\PersonBundle\Entity\Person */
        $person = $this->get('chill.person.repository.person')
            ->find($person_id);
        
        if ($person === null) {
            throw $this->createNotFoundException("The person is not found");
        }
        
        $this->denyAccessUnlessGranted(PersonVoter::SEE, $person);
        
        /* @var $authorizationHelper \Chill\MainBundle\Security\Authorization\AuthorizationHelper */
        $authorizationHelper = $this->get('chill.main.security.'
            . 'authorization.helper');
        
        $circles = $authorizationHelper->getReachableCircles(
            $this->getUser(), 
            new Role(ConsultationVoter::SEE), 
            $person->getCenter()
            );
        
        $consultations = $this->getDoctrine()->getManager()
            ->createQuery('SELECT c FROM ChillHealthBundle:Consultation c '
                . 'WHERE c.patient = :person AND c.circle IN(:circles) '
                . 'ORDER BY c.date DESC')
            ->setParameter('person', $person)
            ->setParameter('circles', $circles)
            ->getResult();
        
        return $this->render('ChillHealthBundle:Consultation:list.html.twig', array(
                'person' => $person,
                'consultations' => $consultations
            ));    
    }

    public function newAction($id)
    {
        return $this->render('ChillHealthBundle:Consultation:new.html.twig', array(
                // ...
            ));    
        
    }
    
    public function showAction($consultation_id, Request $request)
    {   
        /* @var $consultation \Chill\HealthBundle\Entity\Consultation */
        $consultation = $this->get('chill_health.repository_consultation')
            ->find($consultation_id);
        
        if ($consultation === null) {
            throw $this->createNotFoundException("consultation not found");
        }
        
        $this->denyAccessUnlessGranted(ConsultationVoter::SEE, $consultation);
        
        $person = $consultation->getPatient();
        
        $this->denyAccessUnlessGranted(PersonVoter::SEE, $person);
        
        // embed the form if required
        $params = array();
        if ($request->query->has('action')) {
            switch ($request->query->get('action')) {
                case 'medication_add':
                    $params['form_medication'] = $this
                        ->createMedicationForm($consultation)
                        ->createView();
                    break;
                case 'medication_highlight':
                    $params['medication_highlight'][] = $request->query
                        ->getInt('medication_id', null);
                    break;
                case 'suggest_close':
                    $params['form_close'] = $this
                        ->createConsultationCloseForm($consultation)
                        ->createView();
                    break;
                default:
                    throw new \RuntimeException(sprintf("The action '%s' "
                        . "is unknown", $request->query->get('action')));
            }
        }
        
        return $this->render("ChillHealthBundle:Consultation:show.html.twig",
            \array_merge(
                array(
                    'person' => $person,
                    'consultation' => $consultation
                ), 
                $params)
            );
    }
    
    public function closeAction($consultation_id, Request $request)
    {
        /* @var $consultation \Chill\HealthBundle\Entity\Consultation */
        $consultation = $this->get('chill_health.repository_consultation')
            ->find($consultation_id);
        
        if ($consultation === null) {
            throw $this->createNotFoundException("consultation not found");
        }
        
        $this->denyAccessUnlessGranted(ConsultationVoter::SEE, $consultation);
        
        $person = $consultation->getPatient();
        
        $this->denyAccessUnlessGranted(PersonVoter::SEE, $person);
        
        $form = $this->createConsultationCloseForm($consultation);
        
        $form->handleRequest($request);
        
        if ($form->isValid()) {
            $consultation->setState(Consultation::STATE_CLOSED);
            
            $this->getDoctrine()->getManager()
                ->flush();
            
            $this->addFlash(('success'), $this->get('translator')
                ->trans('The consultation is closed.'));
            
            return $this->redirectToRoute('chill_health_consultation_show', 
                [
                    'consultation_id' => $consultation->getId()
                ]);
        }
        
        $this->addFlash('error', $this->get('translator')
            ->trans('The consultation could not be closed.'));
        
        return $this->redirectToRoute('chill_health_consultation_show', 
            [
                'consultation_id' => $consultation->getId(),
                'action' => 'suggest_close'
            ]);
    }
    
    /**
     * 
     * @param \Chill\HealthBundle\Controller\Consultation $consultation
     * @return \Symfony\Component\Form\FormInterface
     */
    protected function createMedicationForm(Consultation $consultation)
    {
        return $this->createForm(
                MedicationType::class, 
                (new Medication())->setConsultation($consultation)
                ,
                [
                    'action' => $this
                        ->generateUrl('chill_health_medication_create'),
                    'method' => 'POST'
                ]
            )
            ->add('submit', SubmitType::class)
            ;
    }
    
    protected function createConsultationCloseForm(Consultation $consultation)
    {
        $builder = $this->createFormBuilder(
            [
                'consultation' => $consultation->getId(),
                'submit' => 'close'
            ], 
            [
                'action' => $this->generateUrl(
                    'chill_health_consultation_close',
                    [
                        'consultation_id' => $consultation->getId()
                    ]),
                'method' => 'POST'
        ])
            ->add('consultation', HiddenType::class)
            ->add('submit', SubmitType::class);
        
        return $builder->getForm();
    }

}

Resources/views/Consultation/list.html.twig
{% extends "ChillPersonBundle::layout.html.twig" %}

{% set activeRouteKey = '' %}

{% block title 'Consultation list'|trans %}

{% block personcontent %}
<h1>{{ 'Consultation list'|trans }}</h1>

{% if consultations|length > 0 %}
<table>
    <thead>
        <tr>
            <td>{{ 'Date'|trans }}</td>
            <td>{{ 'Author'|trans }}</td>
            <td>{{ 'State'|trans }}</td>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        {% for consultation in consultations %}
        <tr>
            <td>{{ consultation.date|localizeddate('long', 'none') }}</td> 
            <td>{{ consultation.author }}</td>
            <td>{{ 'consultation_state_' ~ consultation.state|trans }}</td>
            <td>
                <ul class="record_actions">
                    <li>
                        <a href="{{ path('chill_health_consultation_show', { 'consultation_id' : consultation.id } ) }}" class="sc-button btn-see">
                            {{ 'See'|trans }}
                        </a>
                    </li>
                </ul>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <p class="chill-no-data-statement">{{ "There aren't any consultation yet"|trans }}</p>
{% endif %}

<ul class="record_actions">
    <li>
        <a href="{{ path('chill_health_consultation_new', { 'person_id' : person.id } ) }}">
            {{ 'New consultation' }}
        </a>
    </li>
</ul>

{% endblock %}

Resources/views/Consultation/new.html.twig
{% extends "::base.html.twig" %}

{% block title %}ChillHealthBundle:Consultation:new{% endblock %}

{% block body %}
<h1>Welcome to the Consultation:new page</h1>
{% endblock %}

Resources/views/Consultation/show.html.twig
{% extends "ChillPersonBundle::layout.html.twig" %}

{% set activeRouteKey = '' %}

{% set role_update = constant('Chill\\HealthBundle\\Security\\Authorization\\ConsultationVoter::UPDATE') %}

{% if form_close is defined %}
    {% set is_updatable = false %}
{% else %}
    {% set is_updatable = is_granted(role_update, consultation) %}
{% endif %}

{% block title 'Show consultation'|trans %}

{% block personcontent %}
    <h1>{{ 'Show consultation'|trans }}</h1>

    <dl>
        <dt>{{ 'Date'|trans }}</dt>
        <dd>{{ consultation.date|localizeddate('long', 'none') }}</dd>

        <dt>{{ 'Author'|trans }}</dt>
        <dd>{{ consultation.author }}</dd>

        <dt>{{ 'Circle'|trans }}</dt>
        <dd>{{ consultation.circle.name|localize_translatable_string }}</dd>
    </dl>
    
    <h2>{{ 'Active problems'|trans }}</h2>

    <p>Disponible dans les futures versions...</p>

    <h2>{{ 'Medications'|trans }}</h2>
    
    {% if consultation.medications|length == 0 %}
        <p>
            <span class="chill_no_data_statement">{{ 'No medications' }}</span>
        </p>
    {% else %}
        <table>
            <tbody>
                    {% for medication in consultation.medications %}
                        <tr>
                            <td class="medication-date-from">
                                <dl>
                                    <dt>{{ 'Date from'|trans }}</dt>
                                    <dd>{{ medication.dateFrom|localizeddate('long', 'none') }}</dd>
                                
                                    <dt>{{ 'Drug'|trans }}</dt>
                                    <dd>
                                        {{ medication.substance.displayName|localize_translatable_string }}, {{ medication.doseQuantityValue }}&nbsp;{{ medication.doseQuantityUnit }}
                                    </dd>
                                
                                    <dt>{{ "Fréquence d'administration"|trans }}</dt>
                                    <dd>{{ medication.administrationFrequency }}</dd>
                                
                                    <dt>{{ "Route of administration"|trans }}</dt>
                                    <dd>{{ medication.routeOfAdministration.displayName|localize_translatable_string }}</dd>
                                
                                    <dt>{{ 'Date to'|trans }}</dt>
                                    <dd>{{ medication.dateTo|localizeddate('long', 'none') }}</dd>
                                    
                                    <dt>{{ 'Mode de délivrance'|trans }}</dt>
                                    <dd>
                                        {% if medication.modeDelivrance is not empty%}
                                            <blockquote class="chill-user-quote">
                                            {{ medication.modeDelivrance }}
                                            </blockquote>
                                        {% else %}
                                            <p class="chill-no-data-statement">{{ 'There are no indication'|trans }}</p>
                                        {% endif %}
                                    </dd>
                                </dl>
                                    
                                {% if is_updatable %}
                                <ul class="record_actions">
                                    <li>
                                        <a href="{{ path('chill_health_consultation_show', { 'consultation_id' : consultation.id, 'action': 'medication_update', 'medication_id': medication.id } ) }}" class="sc-button btn-update">
                                            {{ "Update"|trans }}
                                        </a>
                                    </li>
                                </ul>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
    {% endif %}
    
    {% if form_medication is defined %}
    {{ form_start(form_medication) }}
    
    {{ form_row(form_medication.dateFrom) }}
    {{ form_row(form_medication.substance) }}
    {{ form_row(form_medication.substance_string) }}
    {{ form_row(form_medication.doseQuantityValue) }}
    {{ form_row(form_medication.doseQuantityUnit) }}
    {{ form_row(form_medication.routeOfAdministration) }}
    {# {{ form_row(form_medication.administrationUnitCode) }} #}
    {{ form_row(form_medication.administrationFrequency) }}
    {{ form_row(form_medication.dateTo) }}
    {{ form_row(form_medication.modeDelivrance) }}
    {{ form_row(form_medication.neverPublish, { 'label' : 'Allow publication ?' } ) }}
    
    <ul class="record_actions">
        <li>
            {{ form_widget(form_medication.submit, { 'attrs' : { 'class' : 'sc-button bt-create' }, 'label' : 'Submit' } ) }}
        </li>
        <li>
            <a href="{{ path('chill_health_consultation_show', { 'consultation_id' : consultation.id } ) }}" class="sc-button bt-cancel">
                {{ 'Cancel'|trans }}
            </a>
        </li>
    </ul>
    
    {{ form_end(form_medication) }}
    {% endif %}
    
    <!-- CTA for medication sections  -->
    {% if form_medication is not defined and is_updatable %}
    <ul class="record_actions">
        <li>
            <a href="{{ path('chill_health_consultation_show', { 'consultation_id' : consultation.id, 'action': 'medication_add' } ) }}" class="sc-button bt-create" />
            {{ 'Add a medication' }}
            </a>
        </li>
        <li>
            <a href="#" class="sc-button btn-create">
            {{ 'Renew a medication' }}
            </a>
        </li>
    </ul>
    {% endif %}
    
    
    
    
    <h2>{{ 'Actions'|trans }}</h2>
    
    <!-- CTA for consultation -->

    <ul class="record_actions">
        {% if is_updatable %}
        <li>
            <a href="{{ path('chill_health_consultation_show', { 'consultation_id' : consultation.id, 'action' : 'suggest_close' } ) }}" class="sc-button">
              {{ 'Close consultation'|trans }}
            </a>
        </li>
        
        <li>
            <a href="{{ path('chill_health_consultation_close', { 'consultation_id' : consultation.id, 'action': 'suggest_close_and_publish' } ) }}" class="sc-button">
              {{ 'Close consultation and publish document'|trans }}
            </a>
        </li>
        {% endif %}
        
        {% if form_close is defined %}
        <li>
            {{ form_start(form_close) }}
            {{ form_widget(form_close.submit, { 'attrs' : { 'class' : 'sc-button btn-delete' }, 'label': 'Close consultation' } ) }}
            {{ form_end(form_close) }}
        </li>
        {% endif %}
        <li>
            <a href="{{ path('chill_health_consultation_list', { 'person_id': person.id } ) }}" class="sc-button btn-cancel">
                {{ 'Back to the list'|trans }}
            </a>
        </li>
    </ul>
    
    
    
{% endblock %}